### ISSUE TITLE
Custom Climate Component Besmart not working

### ISSUE THREAD

**Issue by faxbio** [muchasuerte/home-assistant#1]
py scripts return errors and do not retrieve (nor send) any data from / to besmart thermostat.

2018-09-05 00:20:02 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 226, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 679, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climate/besmart.py", line 310, in set_temperature
    self._setRoomTemp(temperature)
  File "/config/custom_components/climate/besmart.py", line 163, in _setRoomTemp
    thModel = self._roomData.get('thModel')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by faxbio** [comment]
It was my fault . cleaning cache solved. 
Thx for having shared the code. good job.

**Comment by muchasuerte** [comment]
you are welcome, I developed this custom component many years ago, however it is not yet completed
